#!/usr/bin/env bash
# Write the sandbox's internal router config from the plan.
#
# Nothing here is hardcoded per project, and the domain comes from the
# environment: a Caddyfile with the domain baked into every host matcher makes a
# domain override silently do nothing, which is the single most confusing way for
# this to fail.
#
# TLS terminates at the shared router in front of the sandbox, so this speaks
# plain HTTP on :80 and only has to split by hostname.
set -euo pipefail

LOG_TAG="gen-caddyfile"
# shellcheck source-path=SCRIPTDIR source=lib.sh
source "${SANDBOXER_SCRIPTS:-/opt/sandboxer/scripts}/lib.sh"

OUT="$SANDBOXER_RUN/Caddyfile"
mkdir -p "$SANDBOXER_RUN"

# A named matcher is `@` plus a token, so a label like `admin-api` becomes
# `@admin_api`.
matcher() { printf '@%s\n' "$(printf '%s' "$1" | tr -c 'a-zA-Z0-9_' '_')"; }

# port_of <target> -- a route names either a backend's `name` or any service's
# `label`, and both spellings are useful: a route can point at a backend by name
# or at a long-running front-end by the label it is served under. Name wins, so a
# backend is never shadowed by a front-end that happens to share its label.
port_of() {
  jq -r --arg t "$1" '
    [ .services[]? | select(.kind != "static") ] as $s
    | ( ( $s[] | select(.name == $t) | .port )
      // ( $s[] | select(.label == $t) | .port ) )
    // empty
  ' "$SANDBOXER_PLAN" | sed -n 1p
}

# `sed -n 1p` and not `head -1`: this script runs under `set -o pipefail`, and
# `head` closes the pipe as soon as it has its line, so a `jq` with more to write
# dies of SIGPIPE and the pipeline exits 141 -- which `set -e` turns into "the
# Caddyfile could not be generated" with no cause anywhere. `sed -n 1p` reads to
# EOF.

{
  printf '# Generated by gen-caddyfile.sh from %s. Edits are lost on restart.\n' "$SANDBOXER_PLAN"
  printf '{\n'
  printf '\tauto_https off\n'
  printf '\tadmin off\n'
  printf '\tlog {\n'
  printf '\t\toutput stdout\n'
  printf '\t\tformat console\n'
  printf '\t\tlevel INFO\n'
  printf '\t}\n'
  printf '}\n\n'

  # --- static-serving snippets -------------------------------------------------
  #
  # `root` is set before the `file` matcher in every one of these, because the
  # matcher resolves paths against `root`. Testing for index.html first looks
  # under Caddy's working directory instead, misses, and makes every built app
  # report itself as not built.
  #
  # args: 0 = directory, 1 = label.

  # Static builds are on demand, never at startup, so "not built yet" is a normal
  # state and has to say what to do about it rather than 404. Defined first
  # because a snippet must exist before anything imports it.
  printf '(sandboxer_unbuilt) {\n'
  printf '\trespond `{args[0]} has not been built in this sandbox.\n\n'
  printf 'Run:  sandboxer build %s --app {args[0]}\n' "$SANDBOXER_SLUG"
  printf '` 503\n'
  printf '}\n\n'

  cat <<'SNIPPETS'
# A single-page app: any unknown path is the app's own router's business.
(sandboxer_spa) {
	root * {args[0]}
	@built file /index.html
	handle @built {
		encode zstd gzip
		try_files {path} {path}/ /index.html
		file_server
	}
	handle {
		import sandboxer_unbuilt {args[1]}
	}
}

# A directory of static files. No history fallback: file_server resolves
# index.html for a directory on its own, and an unknown path is a real 404.
(sandboxer_files) {
	root * {args[0]}
	@built file /index.html
	handle @built {
		encode zstd gzip
		file_server
	}
	handle {
		import sandboxer_unbuilt {args[1]}
	}
}

# A static export whose generator does not emit trailing-slash directories, so
# /blog/foo must resolve to foo.html rather than foo/index.html.
(sandboxer_html) {
	root * {args[0]}
	@built file /index.html
	handle @built {
		encode zstd gzip
		try_files {path}.html {path} {path}/index.html
		file_server
	}
	handle {
		import sandboxer_unbuilt {args[1]}
	}
}
SNIPPETS

  printf '\n:80 {\n'

  # --- status surface, on every hostname ---------------------------------------
  # The dashboard reads these through the router, so they must answer while the
  # database is still restoring.
  printf '\thandle /__sandboxer/live {\n\t\trespond "ok" 200\n\t}\n'
  printf '\thandle /__sandboxer/status.json {\n\t\troot * %s\n\t\trewrite * /status.json\n\t\tfile_server\n\t}\n' "$SANDBOXER_RUN"
  printf '\thandle /__sandboxer/built.json {\n\t\troot * %s\n\t\trewrite * /.built.json\n\t\tfile_server\n\t}\n' "$SANDBOXER_WWW"

  # Per-service health, so the dashboard can show which services are up without
  # a port published to the host.
  while read -r record; do
    [[ -z "$record" ]] && continue
    id=$(svc_id "$record")
    port=$(field "$record" port)
    health=$(field "$record" health)
    [[ -z "$port" || -z "$health" ]] && continue
    requested "$record" || continue
    printf '\thandle /__sandboxer/health/%s {\n' "$id"
    printf '\t\trewrite * %s\n' "$health"
    printf '\t\treverse_proxy 127.0.0.1:%s\n' "$port"
    printf '\t}\n'
  done < <(jq -c '.services[]? | select(.kind != "static")' "$SANDBOXER_PLAN")

  # Everything else under /__sandboxer/ is a 404, and this block is why the prefix
  # is reserved (contracts §5.1). `handle` blocks are mutually exclusive and the
  # more specific path wins, so the routes above still answer; what this catches
  # is the paths that named nothing -- above all the health route of a service the
  # plan marks `optional` and nobody requested, which is deliberately not written.
  #
  # Without it those requests fell through to the *app* block for whatever
  # hostname they arrived on, because a host matcher matches any path. What came
  # back was that front-end's own answer: an unbuilt app replied with its 503
  # "not built yet" page, so the dashboard read every dormant service as `down`;
  # and once the app was built the same request got the SPA's index.html and a
  # 200, so the same never-started service read as `up`. Neither answer had
  # anything to do with the service, and the second is the worse one.
  printf '\thandle /__sandboxer/* {\n'
  printf '\t\trespond "sandboxer: no such status route {http.request.uri.path}" 404\n'
  printf '\t}\n'

  # --- one site per app ---------------------------------------------------------
  while read -r record; do
    [[ -z "$record" ]] && continue
    kind=$(field "$record" kind)
    label=$(field "$record" label)
    [[ -z "$label" ]] && continue
    requested "$record" || continue
    m=$(matcher "$label")

    printf '\n\t%s host %s\n' "$m" "$(fqdn "$label")"
    printf '\thandle %s {\n' "$m"

    # Path prefixes first, longest first, so /api/admin never falls into /api.
    # Same-origin paths rather than absolute URLs keep the bundle free of
    # cross-origin requests and take CORS out of the picture entirely.
    while read -r prefix; do
      [[ -z "$prefix" ]] && continue
      target=$(jq -r --arg l "$label" --arg p "$prefix" '.routes[$l][$p] // empty' "$SANDBOXER_PLAN")
      port=$(port_of "$target")
      if [[ -z "$port" ]]; then
        warn "route ${label}${prefix} names '${target}', which holds no port -- skipped"
        continue
      fi
      printf '\t\thandle %s/* {\n' "${prefix%/}"
      printf '\t\t\turi strip_prefix %s\n' "${prefix%/}"
      printf '\t\t\treverse_proxy 127.0.0.1:%s\n' "$port"
      printf '\t\t}\n'
    done < <(jq -r --arg l "$label" '.routes[$l]? // {} | keys[]' "$SANDBOXER_PLAN" |
      awk '{ print length($0), $0 }' | sort -rn | cut -d' ' -f2-)

    printf '\t\thandle {\n'
    case "$kind" in
      static)
        printf '\t\t\timport sandboxer_%s %s/%s "%s"\n' \
          "$(field "$record" static_mode spa)" "$SANDBOXER_WWW" "$label" "$label"
        ;;
      backend | server)
        printf '\t\t\treverse_proxy 127.0.0.1:%s\n' "$(field "$record" port)"
        ;;
    esac
    printf '\t\t}\n'
    printf '\t}\n'
  done < <(jq -c '.services[]?' "$SANDBOXER_PLAN")

  # --- object storage ----------------------------------------------------------
  # `s3` is a reserved label. The console is what makes an upload visible while
  # debugging; the API is what the services talk to.
  if [[ "$(plan .storage.driver none)" == "minio" ]]; then
    printf '\n\t@s3 host %s\n' "$(fqdn s3)"
    printf '\thandle @s3 {\n'
    printf '\t\thandle /console/* {\n'
    printf '\t\t\turi strip_prefix /console\n'
    printf '\t\t\treverse_proxy 127.0.0.1:9001\n'
    printf '\t\t}\n'
    printf '\t\thandle {\n\t\t\treverse_proxy 127.0.0.1:9000\n\t\t}\n'
    printf '\t}\n'
  fi

  # Naming the host matters: the usual cause is a label that is in the router but
  # not in this project's plan, and the 404 is the only place that shows up.
  printf '\n\thandle {\n'
  printf '\t\trespond "sandboxer: no route for {http.request.host}" 404\n'
  printf '\t}\n'
  printf '}\n'
} >"$OUT"

log "wrote $OUT"
