// Heading anchors, GitHub's way.
//
// The pages are read in two places and a link to a section has to work in both,
// so the ids are the ones GitHub's own renderer would produce: lowercased, every
// run of non-alphanumerics collapsed to a single hyphen, the edges trimmed, and a
// numeric suffix when two headings on one page would otherwise collide.
//
// **One slugger produces both the ids in the markup and the ids in the returned
// headings list.** That is not a tidiness point. The table of contents and the
// anchors are generated by different parts of this pipeline, and the collision
// suffix depends on what came before — so two sluggers walking the same page in
// slightly different order produce a contents entry linking to `#setup-2` and a
// heading with the id `#setup-3`, which is a table of contents that scrolls to the
// wrong section and looks like a CSS bug.

/**
 * One heading's text, as an id, before any collision handling.
 *
 * Letters and numbers are matched with the Unicode properties rather than `a-z`
 * and `0-9`, so a heading with an accent in it keeps the accented letter instead
 * of losing the word. GitHub does the same.
 */
export const slugify = (text: string): string =>
  text
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "");

/**
 * The id a heading of entirely punctuation gets.
 *
 * `## ???` slugifies to nothing, and an empty `id` is an anchor that cannot be
 * linked to and a table of contents entry that jumps to the top of the page. It
 * happens: a heading that is a single symbol, or one made only of `<code>` that
 * held nothing but punctuation.
 */
const UNNAMED = "section";

/**
 * A slugger for one page.
 *
 * Stateful on purpose — it remembers what it has already issued, which is the
 * only way to number a collision. Create one per page and never share it, or the
 * second page starts numbering from where the first left off.
 */
export const createSlugger = (): ((text: string) => string) => {
  const seen = new Map<string, number>();

  return (text: string): string => {
    const base = slugify(text) || UNNAMED;
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    // The first one keeps the plain id; the second is `-2`, not `-1`, because a
    // reader looking at two ids called `setup` and `setup-2` can count them.
    return count === 0 ? base : `${base}-${count + 1}`;
  };
};
