/**
 * The certificate the router serves.
 *
 * A sandbox hostname is four labels deep — `<slug>.<label>.<project>.<domain>` —
 * and a wildcard matches exactly one label, so the certificate has to carry a
 * wildcard for every depth rather than one for the domain. Getting that wrong
 * produces a certificate that validates for the dashboard and fails for every
 * sandbox, which reads as a broken sandbox rather than a wrong certificate.
 *
 * mkcert is the only issuer supported, because it is the only one that can make
 * a browser trust a local name without a public DNS record. It is optional:
 * without it the router serves plain http, which is a smaller thing to get
 * working and an honest first milestone.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { nodeRunner, type Runner } from "../docker.js";
import { paths } from "../paths.js";

export interface Certificate {
  certFile: string;
  keyFile: string;
  /** Whether a browser on this machine will accept it without a warning. */
  trusted: boolean;
  /** The issuing tool's root store, for the message that says how to trust it. */
  caRoot?: string | undefined;
}

export interface TlsOptions {
  run?: Runner | undefined;
  env?: NodeJS.ProcessEnv | undefined;
  platform?: NodeJS.Platform | undefined;
}

/**
 * The names one certificate has to cover.
 *
 * Depth matters: `*.sbx.localhost` does not match `app.demo.sbx.localhost`, so
 * every level a hostname can reach needs its own wildcard. Four levels covers
 * `<slug>.<label>.<project>.<domain>` with one to spare.
 */
export function certificateNames(domain: string): string[] {
  return [domain, `*.${domain}`, `*.*.${domain}`, `*.*.*.${domain}`, "localhost", "127.0.0.1", "::1"];
}

/** Whether mkcert is installed and runnable. */
export async function mkcertAvailable(run: Runner = nodeRunner): Promise<boolean> {
  return (await run("mkcert", ["-CAROOT"])).code === 0;
}

async function caRootOf(run: Runner): Promise<string | undefined> {
  const result = await run("mkcert", ["-CAROOT"]);
  if (result.code !== 0) return undefined;
  const root = result.stdout.trim();
  return root === "" ? undefined : root;
}

/**
 * Whether this machine's trust store already accepts mkcert's root.
 *
 * Asked rather than assumed, because installing that root is the one step in the
 * whole setup that needs an administrator password. Knowing the answer is what
 * lets `init` fall back to plain http and print the single command that upgrades
 * it, instead of serving a certificate every browser refuses.
 */
export async function caTrusted(options: TlsOptions = {}): Promise<boolean> {
  const run = options.run ?? nodeRunner;
  const platform = options.platform ?? process.platform;
  const root = await caRootOf(run);
  if (!root) return false;

  const rootCert = join(root, "rootCA.pem");
  if (!existsSync(rootCert)) return false;

  if (platform === "darwin") {
    return (await run("security", ["verify-cert", "-c", rootCert])).code === 0;
  }
  // Elsewhere the honest answer is "the root exists and mkcert manages it".
  // There is no portable query, and claiming otherwise would make the fallback
  // fire on a machine that is already set up.
  return true;
}

/**
 * Issues (or reuses) the wildcard certificate for a domain.
 *
 * Reused when it is already there: re-issuing on every `init` would invalidate
 * the copy a running browser has pinned for the session, for no gain.
 */
export async function ensureCertificate(domain: string, options: TlsOptions = {}): Promise<Certificate | undefined> {
  const run = options.run ?? nodeRunner;
  const env = options.env ?? process.env;
  if (!(await mkcertAvailable(run))) return undefined;

  const dir = paths(env).tls;
  await mkdir(dir, { recursive: true });
  const certFile = join(dir, `${domain}.pem`);
  const keyFile = join(dir, `${domain}-key.pem`);

  if (!existsSync(certFile) || !existsSync(keyFile)) {
    const result = await run("mkcert", ["-cert-file", certFile, "-key-file", keyFile, ...certificateNames(domain)]);
    if (result.code !== 0) return undefined;
  }

  return {
    certFile,
    keyFile,
    trusted: await caTrusted(options),
    caRoot: await caRootOf(run),
  };
}

/** Writes the router's TLS section. Kept beside the issuer so both agree on the paths. */
export async function writeTlsConfig(dynamicDir: string, cert: Certificate, mountedAt: string): Promise<string> {
  const path = join(dynamicDir, "tls.yml");
  await mkdir(dynamicDir, { recursive: true });
  await writeFile(
    path,
    [
      "# Generated by sandboxr init. Edits are lost on the next run.",
      "tls:",
      "  stores:",
      "    default:",
      "      defaultCertificate:",
      `        certFile: ${mountedAt}/${basenameOf(cert.certFile)}`,
      `        keyFile: ${mountedAt}/${basenameOf(cert.keyFile)}`,
      "  certificates:",
      `    - certFile: ${mountedAt}/${basenameOf(cert.certFile)}`,
      `      keyFile: ${mountedAt}/${basenameOf(cert.keyFile)}`,
      "      stores: [default]",
      "",
    ].join("\n"),
  );
  return path;
}

function basenameOf(path: string): string {
  return path.slice(path.lastIndexOf("/") + 1);
}
